@startuml

-> ":UiManager" : start()
activate ":UiManager"

":UiManager" -> ":MainWindow" : fillInnerParts()
activate ":MainWindow"
":MainWindow" -> ":MainWindow" : executeCommand("deleteProc 1 1")
activate ":MainWindow"
":MainWindow" -> ":LogicManager" : execute("deleteProc 1 1")
activate ":LogicManager"

":LogicManager" -> ":AddressBookParser" : parseCommand("deleteProc 1 1 ")
activate ":AddressBookParser"

create ":DeleteProcCommandParser"
":AddressBookParser" -> ":DeleteProcCommandParser" : new DeleteProcCommandParser()
activate ":DeleteProcCommandParser"
create ":DeleteProcCommand"
":DeleteProcCommandParser" -> ":DeleteProcCommand" : parse("1 1")
activate ":DeleteProcCommand"

":DeleteProcCommand" --> ":DeleteProcCommandParser"
deactivate ":DeleteProcCommand"
":DeleteProcCommandParser" --> ":AddressBookParser"
deactivate ":DeleteProcCommandParser"
":AddressBookParser" --> ":LogicManager"
deactivate ":AddressBookParser"
":LogicManager" --> ":MainWindow"

":LogicManager" -> ":DeleteProcCommand" : execute(command)
activate ":DeleteProcCommand"
":DeleteProcCommand" -> ":Model" : getFilteredClientList()
activate ":Model"
":Model" --> ":DeleteProcCommand"
deactivate ":Model"
":DeleteProcCommand" -> ":DeleteProcCommand" : editclientProcedure(clientToEdit)
activate ":DeleteProcCommand"
create ":Client"
":DeleteProcCommand" -> ":Client" : new Client(updatedName, updatedPhone, updatedEmail, updatedAddress, updatedPlan, updatedTags, updatedProcedures)
activate ":Client"
":Client" --> ":DeleteProcCommand"
deactivate ":Client"
":DeleteProcCommand" --> ":DeleteProcCommand"
deactivate ":DeleteProcCommand"

":DeleteProcCommand" -> ":Model" : setClient(clientToEdit, editedClient)
activate ":Model"
":Model" -> ":AddressBook" : setClient(target, editedClient)
activate ":AddressBook"
":AddressBook" --> ":Model"
deactivate ":AddressBook"
":Model" --> ":DeleteProcCommand"
deactivate ":Model"

":DeleteProcCommand" -> ":Model" : updateFilteredClientList(PREDICATE_SHOW_ALL_CLIENTS)
activate ":Model"
":Model" --> ":DeleteProcCommand"
deactivate ":Model"
":DeleteProcCommand" --> ":LogicManager" : CommandResult(message, List<Procedure>)

":LogicManager" -> ":Model" : getAddressBook()
activate ":Model"
":Model" --> ":LogicManager" : addressBook
deactivate ":Model"

":LogicManager" -> ":Storage" : saveAddressBook(addressBook)
activate ":Model"
":Model" --> ":LogicManager"
deactivate ":Model"

":LogicManager" --> ":MainWindow"

deactivate ":LogicManager"
":MainWindow" --> ":MainWindow"
deactivate ":MainWindow"
":MainWindow" --> ":UiManager"
deactivate ":MainWindow"
<-- ":UiManager"
deactivate ":UiManager"
@enduml
